<?xml version="1.0" encoding="UTF-8"?>
    <source package="java.lang">
        <class name="ArithmeticException" line="28">
            <extends class="RuntimeException"/>
            <javadoc line="28">
                Thrown when an exceptional arithmetic condition has occurred. For
                  example, an integer &quot;divide by zero&quot; throws an
                  instance of this class.{@code ArithmeticException} objects may be constructed by the
                  virtual machine as if {@linkplain Throwable#Throwable(String,Throwable,boolean,boolean) suppression were disabled and/or the
                  stack trace was not writable}.                
                <author>
                    unascribed                    
                </author>
                <since>
                    JDK1.0                    
                </since>
            </javadoc>
            <declaration name="serialVersionUID" type="long" line="42"/>
            <javadoc line="44">
                Constructs an {@code ArithmeticException} with no detail
                  message.                
            </javadoc>
            <method name="ArithmeticException" type="constructor" line="48"/>
            <javadoc line="52">
                Constructs an {@code ArithmeticException} with the specified
                  detail message.                
                <param>
                    s   the detail message.                    
                </param>
            </javadoc>
            <method name="ArithmeticException" type="constructor" line="58">
                <params>
                    <param name="s" type="String"/>
                </params>
            </method>
        </class>
    </source>