<?xml version="1.0" encoding="UTF-8"?>
    <source package="org.apache.commons.math3.util">
        <import package="org.apache.commons.math3.exception.MaxCountExceededException"/>
        <import package="org.apache.commons.math3.exception.TooManyEvaluationsException"/>
        <import package="org.junit.Assert"/>
        <import package="org.junit.Test"/>
        <class name="IncrementorTest" line="21">
            <javadoc line="21">
                Test for {@link Incrementor}.                
            </javadoc>
            <method name="testConstructor1" type="void" line="26">
                <declaration name="i" type="Incrementor" line="27"/>
            </method>
            <method name="testConstructor2" type="void" line="33">
                <declaration name="i" type="Incrementor" line="34"/>
            </method>
            <method name="testCanIncrement1" type="void" line="40">
                <declaration name="i" type="Incrementor" line="41"/>
            </method>
            <method name="testCanIncrement2" type="void" line="52">
                <comment line="53">
                    Must keep try/catch because the exception must be generated here,                    
                </comment>
                <comment line="53">
                    and not in the previous loop.                    
                </comment>
                <declaration name="i" type="Incrementor" line="53"/>
                <scope line="54"/>
                <scope line="60"/>
                <scope line="63"/>
            </method>
            <method name="testAccessor" type="void" line="69">
                <declaration name="i" type="Incrementor" line="70"/>
            </method>
            <method name="testBelowMaxCount" type="void" line="78">
                <declaration name="i" type="Incrementor" line="79"/>
            </method>
            <method name="testAboveMaxCount" type="void" line="90">
                <declaration name="i" type="Incrementor" line="91"/>
            </method>
            <method name="testAlternateException" type="void" line="101">
                <anonymous_class line="103">
                    <javadoc line="104">
                        {@inheritDoc}                        
                    </javadoc>
                    <method name="trigger" type="void" line="105"/>
                </anonymous_class>
                <declaration name="cb" type="Incrementor.MaxCountExceededCallback" line="102"/>
                <declaration name="i" type="Incrementor" line="110"/>
            </method>
            <method name="testReset" type="void" line="115">
                <declaration name="i" type="Incrementor" line="116"/>
            </method>
            <method name="testBulkIncrement" type="void" line="128">
                <declaration name="i" type="Incrementor" line="129"/>
            </method>
        </class>
    </source>