<?xml version="1.0" encoding="UTF-8"?>
    <source package="java.io">
        <class name="WriteAbortedException" line="28">
            <extends class="ObjectStreamException"/>
            <javadoc line="28">
                Signals that one of the ObjectStreamExceptions was thrown during a
                  write operation.  Thrown during a read operation when one of the
                  ObjectStreamExceptions was thrown during a write operation.  The
                  exception that terminated the write can be found in the detail
                  field. The stream is reset to it&apos;s initial state and all references
                  to objects already deserialized are discarded.
                  &lt;p&gt;As of release 1.4, this exception has been retrofitted to conform to
                  the general purpose exception-chaining mechanism.  The &quot;exception causing
                  the abort&quot; that is provided at construction time and
                  accessed via the public {@link #detail} field is now known as the
                  &lt;i&gt;cause&lt;/i&gt;, and may be accessed via the {@link Throwable#getCause()}method, as well as the aforementioned &quot;legacy field.&quot;                
                <author>
                    unascribed                    
                </author>
                <since>
                    JDK1.1                    
                </since>
            </javadoc>
            <declaration name="serialVersionUID" type="long" line="47"/>
            <declaration name="detail" type="Exception" line="49"/>
            <javadoc line="49">
                Exception that was caught while writing the ObjectStream.
                  &lt;p&gt;This field predates the general-purpose exception chaining facility.
                  The {@link Throwable#getCause()} method is now the preferred means of
                  obtaining this information.                
                <serial>
                                        
                </serial>
            </javadoc>
            <javadoc line="60">
                Constructs a WriteAbortedException with a string describing
                  the exception and the exception causing the abort.                
                <param>
                    s   String describing the exception.                    
                </param>
                <param>
                    ex  Exception causing the abort.                    
                </param>
            </javadoc>
            <method name="WriteAbortedException" type="constructor" line="66">
                <params>
                    <param name="s" type="String"/>
                    <param name="ex" type="Exception"/>
                </params>
                <comment line="69">
                    Disallow subsequent initCause                    
                </comment>
            </method>
            <javadoc line="72">
                Produce the message and include the message from the nested
                  exception, if there is one.                
            </javadoc>
            <method name="getMessage" type="String" line="76"/>
            <javadoc line="83">
                Returns the exception that terminated the operation (the &lt;i&gt;cause&lt;/i&gt;).                
                <return>
                    the exception that terminated the operation (the &lt;i&gt;cause&lt;/i&gt;),
                      which may be null.                    
                </return>
                <since>
                    1.4                    
                </since>
            </javadoc>
            <method name="getCause" type="Throwable" line="90"/>
        </class>
    </source>