<?xml version="1.0" encoding="UTF-8"?>
    <source package="javax.security.sasl">
        <class name="AuthenticationException" line="2">
            <extends class="SaslException"/>
            <javadoc line="2">
                This exception is thrown by a SASL mechanism implementation
                  to indicate that the SASL
                  exchange has failed due to reasons related to authentication, such as
                  an invalid identity, passphrase, or key.
                  &lt;p&gt;
                  Note that the lack of an AuthenticationException does not mean that
                  the failure was not due to an authentication error.  A SASL mechanism
                  implementation might throw the more general SaslException instead of
                  AuthenticationException if it is unable to determine the nature
                  of the failure, or if does not want to disclose the nature of
                  the failure, for example, due to security reasons.                
                <since>
                    1.5                    
                </since>
                <author>
                    Rosanna Lee                    
                </author>
                <author>
                    Rob Weltman                    
                </author>
            </javadoc>
            <javadoc line="19">
                Constructs a new instance of &lt;tt&gt;AuthenticationException&lt;/tt&gt;.
                  The root exception and the detailed message are null.                
            </javadoc>
            <method name="AuthenticationException" type="constructor" line="23"/>
            <javadoc line="26">
                Constructs a new instance of &lt;tt&gt;AuthenticationException&lt;/tt&gt;
                  with a detailed message.
                  The root exception is null.                
                <param>
                    detail A possibly null string containing details of the exception.                    
                </param>
                <see>
                    java.lang.Throwable#getMessage                    
                </see>
            </javadoc>
            <method name="AuthenticationException" type="constructor" line="33">
                <params>
                    <param name="detail" type="String"/>
                </params>
            </method>
            <javadoc line="36">
                Constructs a new instance of &lt;tt&gt;AuthenticationException&lt;/tt&gt; with a detailed message
                  and a root exception.                
                <param>
                    detail A possibly null string containing details of the exception.                    
                </param>
                <param>
                    ex A possibly null root exception that caused this exception.                    
                </param>
                <see>
                    java.lang.Throwable#getMessage                    
                </see>
                <see>
                    #getCause                    
                </see>
            </javadoc>
            <method name="AuthenticationException" type="constructor" line="44">
                <params>
                    <param name="detail" type="String"/>
                    <param name="ex" type="Throwable"/>
                </params>
            </method>
            <declaration name="serialVersionUID" type="long" line="47"/>
            <javadoc line="47">
                Use serialVersionUID from JSR 28 RI for interoperability                
            </javadoc>
        </class>
    </source>