<?xml version="1.0" encoding="UTF-8"?>
    <source package="javax.naming">
        <class name="AuthenticationException" line="28">
            <extends class="NamingSecurityException"/>
            <javadoc line="28">
                This exception is thrown when an authentication error occurs while
                  accessing the naming or directory service.
                  An authentication error can happen, for example, when the credentials
                  supplied by the user program is invalid or otherwise fails to
                  authenticate the user to the naming/directory service.
                  &lt;p&gt;
                  If the program wants to handle this exception in particular, it
                  should catch AuthenticationException explicitly before attempting to
                  catch NamingException. After catching AuthenticationException, the
                  program could reattempt the authentication by updating
                  the resolved context&apos;s environment properties with the appropriate
                  appropriate credentials.
                  &lt;p&gt;
                  Synchronization and serialization issues that apply to NamingException
                  apply directly here.                
                <author>
                    Rosanna Lee                    
                </author>
                <author>
                    Scott Seligman                    
                </author>
                <since>
                    1.3                    
                </since>
            </javadoc>
            <javadoc line="51">
                Constructs a new instance of AuthenticationException using the
                  explanation supplied. All other fields default to null.                
                <param>
                    explanation     A possibly null string containing
                      additional detail about this exception.                    
                </param>
                <see>
                    java.lang.Throwable#getMessage                    
                </see>
            </javadoc>
            <method name="AuthenticationException" type="constructor" line="59">
                <params>
                    <param name="explanation" type="String"/>
                </params>
            </method>
            <javadoc line="63">
                Constructs a new instance of AuthenticationException.
                  All fields are set to null.                
            </javadoc>
            <method name="AuthenticationException" type="constructor" line="67"/>
            <declaration name="serialVersionUID" type="long" line="71"/>
            <javadoc line="71">
                Use serialVersionUID from JNDI 1.1.1 for interoperability                
            </javadoc>
        </class>
    </source>