<?xml version="1.0" encoding="UTF-8"?>
    <source package="java.awt.print">
        <import package="java.io.IOException"/>
        <class name="PrinterIOException" line="29">
            <extends class="PrinterException"/>
            <javadoc line="29">
                The &lt;code&gt;PrinterIOException&lt;/code&gt; class is a subclass of{@link PrinterException} and is used to indicate that an IO error
                  of some sort has occurred while printing.
                  &lt;p&gt;As of release 1.4, this exception has been retrofitted to conform to
                  the general purpose exception-chaining mechanism.  The
                  &quot;&lt;code&gt;IOException&lt;/code&gt; that terminated the print job&quot;
                  that is provided at construction time and accessed via the{@link #getIOException()} method is now known as the &lt;i&gt;cause&lt;/i&gt;,
                  and may be accessed via the {@link Throwable#getCause()} method,
                  as well as the aforementioned &quot;legacy method.&quot;                
            </javadoc>
            <declaration name="serialVersionUID" type="long" line="43"/>
            <declaration name="mException" type="IOException" line="45"/>
            <javadoc line="45">
                The IO error that terminated the print job.                
                <serial>
                                        
                </serial>
            </javadoc>
            <javadoc line="51">
                Constructs a new &lt;code&gt;PrinterIOException&lt;/code&gt;
                  with the string representation of the specified{@link IOException}.                
                <param>
                    exception the specified &lt;code&gt;IOException&lt;/code&gt;                    
                </param>
            </javadoc>
            <method name="PrinterIOException" type="constructor" line="57">
                <params>
                    <param name="exception" type="IOException"/>
                </params>
                <comment line="59">
                    Disallow subsequent initCause                    
                </comment>
            </method>
            <javadoc line="62">
                Returns the &lt;code&gt;IOException&lt;/code&gt; that terminated
                  the print job.
                  &lt;p&gt;This method predates the general-purpose exception chaining facility.
                  The {@link Throwable#getCause()} method is now the preferred means of
                  obtaining this information.                
                <return>
                    the &lt;code&gt;IOException&lt;/code&gt; that terminated
                      the print job.                    
                </return>
                <see>
                    IOException                    
                </see>
            </javadoc>
            <method name="getIOException" type="IOException" line="74"/>
            <javadoc line="78">
                Returns the the cause of this exception (the &lt;code&gt;IOException&lt;/code&gt;
                  that terminated the print job).                
                <return>
                    the cause of this exception.                    
                </return>
                <since>
                    1.4                    
                </since>
            </javadoc>
            <method name="getCause" type="Throwable" line="85"/>
        </class>
    </source>