<?xml version="1.0" encoding="UTF-8"?>
    <source package="sun.security.provider">
        <import package="java.security.AccessController"/>
        <import package="java.security.PrivilegedAction"/>
        <import package="java.security.URIParameter"/>
        <import package="javax.security.auth.login.Configuration"/>
        <import package="javax.security.auth.login.ConfigurationSpi"/>
        <import package="javax.security.auth.login.AppConfigurationEntry"/>
        <import package="com.sun.security.auth.login.ConfigFile"/>
        <class name="ConfigSpiFile" line="38">
            <extends class="ConfigurationSpi"/>
            <javadoc line="38">
                This class wraps the ConfigFile subclass implementation of Configuration
                  inside a ConfigurationSpi implementation that is available from the
                  SUN provider via the Configuration.getInstance calls.                
            </javadoc>
            <declaration name="cf" type="ConfigFile" line="46"/>
            <method name="ConfigSpiFile" type="constructor" line="49">
                <params>
                    <param name="params" type="Configuration.Parameters"/>
                </params>
                <comment line="52">
                    call in a doPrivileged
                    
                     we have already passed the Configuration.getInstance
                     security check.  also this class is not freely accessible
                     (it is in the &quot;sun&quot; package).
                    
                     we can not put doPrivileged calls into
                     ConfigFile because it is a public com.sun class                    
                </comment>
                <comment line="80">
                    if ConfigFile threw a standalone SecurityException
                     (no cause), re-throw it.
                    
                     ConfigFile chains checked IOExceptions to SecurityException.                    
                </comment>
                <comment line="90">
                    unrecognized cause                    
                </comment>
                <comment line="94">
                    if ConfigFile throws some other RuntimeException,
                     let it percolate up naturally.                    
                </comment>
                <scope line="60">
                    <anonymous_class line="61">
                        <method name="run" type="Void" line="62">
                            <scope line="63"/>
                            <scope line="65">
                                <scope line="66"/>
                                <declaration name="uriParam" type="URIParameter" line="70"/>
                            </scope>
                        </method>
                    </anonymous_class>
                </scope>
                <scope line="77">
                    <declaration name="cause" type="Throwable" line="84"/>
                    <scope line="85"/>
                </scope>
            </method>
            <method name="engineGetAppConfigurationEntry" type="AppConfigurationEntry[]" line="98">
                <params>
                    <param name="name" type="String"/>
                </params>
            </method>
            <method name="engineRefresh" type="void" line="102"/>
        </class>
    </source>