<?xml version="1.0" encoding="UTF-8"?>
    <source package="com.sun.jdi">
        <class name="InternalException" line="28">
            <extends class="RuntimeException"/>
            <javadoc line="28">
                Thrown to indicate that an unexpected internal error has
                  occurred.                
                <author>
                    Gordon Hirsch                    
                </author>
                <since>
                    1.3                    
                </since>
            </javadoc>
            <declaration name="errorCode" type="int" line="36"/>
            <method name="InternalException" type="constructor" line="38"/>
            <method name="InternalException" type="constructor" line="43">
                <params>
                    <param name="s" type="String"/>
                </params>
            </method>
            <method name="InternalException" type="constructor" line="48">
                <params>
                    <param name="errorCode" type="int"/>
                </params>
            </method>
            <method name="InternalException" type="constructor" line="53">
                <params>
                    <param name="s" type="String"/>
                    <param name="errorCode" type="int"/>
                </params>
            </method>
            <method name="errorCode" type="int" line="58"/>
        </class>
    </source>